//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEUCHUYEN
    {
        public int MaDC { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string LyDo { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaPB { get; set; }
        public Nullable<int> MaPB2 { get; set; }
    }
}
