//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNGLUONG
    {
        public int MaUL { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Ngay { get; set; }
        public Nullable<double> SoTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
